### ISSUE TITLE
Multistore awareness

### ISSUE THREAD

**Issue by youhost** [GetResponse/GetResponse-PrestaShop-Integration#2]
Hello,
I use prestashop in multistore mode, so it would be useful to have an ID store awareness implemented in the module.
So I could define Connection settings for each store and not mix all subscribers from different stores on the same list.
Is it possible?
Thank you

**Comment by gstruczynski** [comment]
Hello,
There are different settings for each store. You can select different campaign or even different api key in integration settings. So you will not mixed your subscribers, they will be added to defined campaign for each store.
Should you have any other questions, do not hesitate to ask and we will be happy to help.

**Comment by youhost** [comment]
Hello Grzegorz,
thank you for your answer.

I run GetResponse module v4.0.0 on prestashop 1.6.1.4 and, as far as I can see if I change one settings.
This is the test I’ve done:
I connect store A to list A
I switch to store B and connect to list B
I come back to store A
store A is connected to list B :(

May be I use the wrong version or miss some settings?
Thank you

**Comment by gstruczynski** [comment]
Hello,
We fixed this problem. please download the latest release 4.0.1:
https://github.com/GetResponse/GetResponse-PrestaShop-Integration/releases/tag/v4.0.1

Please let us know if now everything works fine

**Comment by youhost** [comment]
Hello Grzegorz,
thank you for the quick fix.
I’ve downloaded the 4.0.1 but on my server the module was not loaded by prestashop.
So I’ve restore 4.0.0 version and it works fine.
Then I copied the files using ftp but still no detection by prestashop on 4.0.1

So I overwrote files in the getresponse 4.0.0 folder.

The settings are now store aware but it seems not possible to select a campaign properly.
I set a campaign, click save, page reload and always pickup the first list in the dropdown.

Am I missing some new tables or fields? 
ps_getresponse_webform
ps_getresponse_settings
ps_getresponse_customs
ps_getresponse_automation

Thank you

**Comment by mzubrzycki** [comment]
Hello Youhost,

Thank you for contacting us. We just released new version of our plugin, v4.0.2. You can download it here -> https://github.com/GetResponse/GetResponse-PrestaShop-Integration/releases/tag/v4.0.2

In order to make this work you need to make several consecutive steps.
1. First of all, you should enable Multistore feature in Prestashop.
2. Please **uninstall** and **delete** old version of our plugin. This is **very** important.
3. Then you need to upload our new plugin to your webserver path: {prestashop}/modules/getresponse. You can do it manually or you can use Presta "Add new module" feature (http://screencast.com/t/oJyFn8sLer - before upload please rename .zip archive to 'getresponse')
4. Please **install** and **enable** our plugin in **every** multistore that you have.
5. Now you should be able to save different settings for each of your stores.

Please let us know it this helps.
If you still experience any problems I suggest to contact us at getresponse-devzone@cs.getresponse.com

Best regards,
Michal.

**Comment by youhost** [comment]
Hello Michal,
Great job, I’ve followed the procedure and everything works fine, thank you very much!

Just one last question, in the tab "export Customers” it is written in a blue frame:
   Each customer export includes all entries from your PrestaShop database.

Does it means that if I export the customers in a campaign using this function, this export process won’t be restricted to the customers from a single store?

Best regards
Joseph

**Comment by gstruczynski** [comment]
Hello Joseph,

"Each customer export includes all entries from your PrestaShop database." means that all kind of customers will be exported: accounts, guests, active, deleted.. it's disposable import which get everything.. of course within active store.

Export will be restricted to the customers from a single store.

Please feel free to contact me again if you have any
questions. I'll be happy to help.

**Comment by youhost** [comment]
Hello Grzegorz,
I confirm everything works perfectly.
I also tested the integration of forms and the embedding is really easy.
Thank you for your support!
Joseph

**Comment by gstruczynski** [comment]
Hi Joseph,

It's good to hear that everything works fine now :)

For the most efficient service, we are changing this ticket status to “solved”.
If you need any further assistance, please don’t hesitate to reopen this ticket!
